### ISSUE TITLE
alpha4 camera takes an abnormally long amount of time to load

### ISSUE THREAD

**Issue by cmd512** [AndreiLux/Perseus-UNIVERSAL5410#12]
Most noticeable after extended use. Also, noticed burst / best picture modes (where burst shot is used) becomes extremely delayed (a good 10-15 seconds). All were much faster on v3.4.

Suspect new tweaked LMK / swap file implementation in alpha4.

**Comment by AndreiLux** [comment]
Since stock kernel users are reporting this too on MF8, I'll conclude it has nothing to do with Perseus for now.

**Comment by cmd512** [comment]
I used the stock kernel for several days previously and did not have this issue.  I believe they are more complaining that the "camera launch isn't instant," which it has never been.  However, on Perseus after extensive use, it lags to the point where I had to do a hard reboot with the power button one time.

**Comment by AndreiLux** [comment]
http://forum.xda-developers.com/showthread.php?p=42968796&highlight=black#post42968796

Sounds like the same issue. Plus I've heard complaints about camera on Wanam.

**Comment by cmd512** [comment]
Actually no, that's just the laggy behavior that unfortunately has always been there.  To clarify:

Normal behavior after extensive use on stock kernel + v3.4:
Open camera, wait 5-10 seconds (shows black screen at the time), camera image appears + camera functions as normal

Abnormal behavior after extensive use on alpha4:
Open camera, wait 30+ seconds (shows black screen the entire time and system is non-responsive), camera image finally appears.  However, if you use any burst shot modes (ie, "best shot"), there is another good 5-10 second delay after you click on the "take photo" button.  One time, the black screen lag was so long (exceeded 1:30 minutes), I had to hold down the power button to power cycle.

Hopefully this helps to clarify, cheers.
