### ISSUE TITLE
"Camera has failed" after flashing to alpha 4. 

### ISSUE THREAD

**Issue by geezadw** [AndreiLux/Perseus-UNIVERSAL5410#13]
Had the same problem on previous version but you released a patch and after installing that it worked. Read back to previous patch and you say its fixed in alpha 4, seems it isn't. GT-19000. Going to try running your old patch and seeing what happens!

**Comment by geezadw** [comment]
Just flashed on the previous patch, seeing what is what now.... Camera has failed! No avail. Will reflash to original alpha 4 now to make sure it's on correct files.

**Comment by geezadw** [comment]
Tried using multiple camera apps and all fail to work. Only happened after alpha 4. Deffo kernel related.

**Comment by geezadw** [comment]
Flashed back to 3.4 and everything is fine and dandy. 0second load time on camera (never had that in my life, haha!) I think it's because alpha 4 kept the vnswap disk size at 0MB.

**Comment by AndreiLux** [comment]
Read the damn instructions and stop spamming the issue tracker.

If you're on a <MEA ROM or have the old patch you need to flash the new firmware files as linked in the changelog.

**Comment by geezadw** [comment]
You do realise you only give a link on the forums. Maybe you should consider constructing things better? I didn't spam the log. I tried to fix it myself and give you some idea to what was wrong. Unlike every other bug posted, I didn't go "WTF IT DON'T WORK"

**Comment by AndreiLux** [comment]
Shut up and learn to read; it's clearly stated in the changelog:

_"Updated ISP kernel drivers. Camera libraries should be updated to => MF3 versions. Here's a CWM for the reverse-fix."_

Everybody else managed to understand it, it was even discussed in the forum, and without having to open an issue.

This platform is not for me to spoon-feed you and hold your hands through your problems, it's for confirmed, reproducible, and technically related issues.

Please apply some common sense to your postings.

**Comment by geezadw** [comment]
You really are a dickhead. I think I'll be swapping kernels. I did read the change log and what I read made no sense to me whats so ever. I also checked about 10/15 pages on the thread and it was just all complaints about the camera..

**Comment by AndreiLux** [comment]
Fuck off already.

**Comment by dorimanx** [comment]
Agree with  AndreiLux! 
GO and make your own kernel!
i get this shit by mail every morning!
go to XDA and whine there! this is DEV only world.
