### ISSUE TITLE
Set on boot option

### ISSUE THREAD

**Issue by dazkyl** [AndreiLux/Perseus-UNIVERSAL5410#15]
What is the theory behind all this ? I mean i overclocked my BIG.cpu from 1.6 all the way up to 1.9 , and while my set on boot option is not ticked , i rebooted my phone and when i opened stweaks again after the phone was rebooted,the cpu max frequency was still the way i left it before i rebooted (1.9).

Why did the cpu frequency stayed the same after a reboot despite the fact my set on boot option isnt ticked?

Cheers.

**Comment by AndreiLux** [comment]
Do you people have a severe lack reading comprehension?

If you move your eyes two lines above the set on boot option, you will find this:

> Apply the settings on boot only if the desired settings prove to be stable, else the device ends up in a boot-loop. **If turned off, the displayed values do not correspond the current live values but the saved profile values**, some inconsistencies may occur on applying.**

**Comment by dazkyl** [comment]
I read that. As i understand , when un-ticked ,  isnt the cpu frequency suppose to reset?

Sorry for the lack of understandment , but i did not understand the statment ''Apply the settings on boot only if the desired settings prove to be stable, else the device ends up in a boot-loop. If turned off, the displayed values do not correspond the current live values but the saved profile values, some inconsistencies may occur on applying.'' correctly. 

Thats why i asked.
