### ISSUE TITLE
"Camera failed" message on <MEA ROMs Running alpha7.2

### ISSUE THREAD

**Issue by DashBlacK** [AndreiLux/Perseus-UNIVERSAL5410#17]
Hello AndreiLux,

I am running the I9500XXUAMDK version of the ROM, which is a <MEA ROM. I just flashed your kernel for the first time. I've flashed the alpha7.2 version and I'm receiving the error message stating "Camera failed". I browsed through some older issues similar to this one and found a fix by replacing the FIMC-IS firmware files. But this is happening on a <MEA ROM so therefore that fix will be useless. I'm assuming you've updated the kernel to support the newer firmware files. I would test this theory by replacing the firmware files from a newer ROM, but I'm on vacation and do not have access to a fast internet connection.

Thank you,
- DashBlacK.

**Comment by AndreiLux** [comment]
There's a fix for older ROMs in the Dropbox folder and in the changelog.
