### ISSUE TITLE
Provision to Disable-Enable "Unsafe Volume pop-up" [Enhancement]

### ISSUE THREAD

**Issue by vincentemerald** [AndreiLux/Perseus-UNIVERSAL5410#18]
Andrei,

would it be possible to include this simple configurable item to enable-disable the "Unsafe Volume Pop-up". This configuration object is supposed to be a system parameter "config_safe_media_volume_enabled" . Can be set to true or false to toggle this parameter. .Probably this could be put in the Stweaks "Audio" tab. Appreciate your support in this regard.

thanks,
Vincent.

**Comment by AndreiLux** [comment]
This has nothing to do with the kernel. Use nettach xposed mod for it.

**Comment by vincentemerald** [comment]
Thanks andrei...was able to install the mod...thanks again! cheers!
