### ISSUE TITLE
Configurable charging current

### ISSUE THREAD

**Issue by sorgelig** [AndreiLux/Perseus-UNIVERSAL5410#19]
Would be good to have this option for 2 reasons:
1) non-official charger
2) USB charging (i have externally powered USB hub).

**Comment by AndreiLux** [comment]
Yes sure I'm still planning to get things feature equivalent to the Midas kernels. When I get back in a week. Wasn't such a high priority thing on this device.

**Comment by AndreiLux** [comment]
Live in alpha9.
