### ISSUE TITLE
Reduce voltage ranges in STweaks for easier adjusting

### ISSUE THREAD

**Issue by sorgelig** [AndreiLux/Perseus-UNIVERSAL5410#20]
It seams the ranges of voltages are too big to adjust. I have to click many times on adjuster to get required value. It's extremely hard.

May be it will be better to set reasonable range for every frequency and thus reduce amount of steps. I think, no CPU can work with voltage 200mv below nominal for specific frequency. The same for overvolting.

**Comment by AndreiLux** [comment]
Fixed with fine-grained slider controls in Synapse as of alpha10.
