### ISSUE TITLE
STweaks: empty entry in GPU max frequency setting.

### ISSUE THREAD

**Issue by sorgelig** [AndreiLux/Perseus-UNIVERSAL5410#25]
STweaks displays empty entry in GPU max frequency setting.

Here is the fix:
https://gist.github.com/sorgelig/6294673

**Comment by AndreiLux** [comment]
I don't consider this a bug in the kernel since that's part of the default driver.

The fix can be done in the generator script without touching the kernel:

> `while read FREQ; do
>   [[ ! -z $FREQ ]] && echo '<spinnerItem name="'$FREQ' MHz" value="'$FREQ'"/>'
> done < /sys/devices/platform/pvrsrvkm.0/sgx_dvfs_table`
