### ISSUE TITLE
Quick toggle Android logger

### ISSUE THREAD

**Issue by sorgelig** [AndreiLux/Perseus-UNIVERSAL5410#26]
I found this feature useful. Especially for those who don't need debugging.
And it's easy to add.

It's from Adam kernel:
https://github.com/wanam/Adam-Kernel-GS4/commit/a318deaee43f47c6b048f01d55d91ed007facce0
https://github.com/wanam/Adam-Kernel-GS4/commit/f5ac31870bc38d640e9f50f9521a41c85ac49e41

**Comment by AndreiLux** [comment]
What's the reason for this?

(Btw just use labels instead of [tags])

**Comment by AndreiLux** [comment]
Well whatever, I'm still not a huge believer of the overhead that logging may cause.

Here's a proper version of the same functionality without the idiotic coding style and which also is faster by avoiding file operation blocking at the IO level.

logger: Add an enable toggle for entry storage https://github.com/AndreiLux/Perseus-UNIVERSAL5410/commit/7c1d084c6ba3cf6b0710527cdba550e3af8c29e5

Enable/disable via `/sys/module/logger/parameters/enabled`
