### ISSUE TITLE
very bad performance when using stock browser

### ISSUE THREAD

**Issue by realcrazycat** [AndreiLux/Perseus-UNIVERSAL5410#27]
CPU always running at a very low frequency,and it can't switch to other governors. when   using stock browsers , it always lag and has a low fps

**Comment by realcrazycat** [comment]
The governors should be better.It should include more governors.

**Comment by AndreiLux** [comment]
> The governors should be better.It should include more governors.

Go buy yourself a i9505 and ask one of the developers on that forum.
