### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by AndreiLux** [AndreiLux/Perseus-UNIVERSAL5410#31]
Post any general questions here.

**Comment by Anakha56** [comment]
Not to take the kernel side further off topic I just wanted to say I have officially tried all the recoveries that I could possibly find for our phones and they all give me the no sound issue. For me to get the no sound issue was easy. After flashing the recovery and letting the phone boot I then switched it off and went into the recovery and did a nandroid, once that completed I rebooted and voila no sound. I think I am going to get into the habit of switching the phone off & on once a day that way I will get sound. Thanks for your recovery Andrei but it did not help :).

**Comment by friedbamboo** [comment]
Want to know whether chinese duo version of S4 i9502 using the same cpu can flash this kernal. Could you please help out?

**Comment by AndreiLux** [comment]
No you can't, the devices are different. Go ask this guy: https://github.com/maxfu

**Comment by friedbamboo** [comment]
Thx a lot~

**Comment by Anakha56** [comment]
Andrei I am running the latest Wanam build and every time i restart the phone the phone does an additional hot boot and I get told something about my Synapse settings settings failed to boot. Now I have not done any overclocking or or under/over volting so it is dead on stock. The last time it occured I underclocked to 1.4 and it still happened, any ideas? I took a look in Root Explorer in the data folder and I saw a folder called .adamkernel so I tried removing it and had android process acore stop working. Does Synapse leave a log when it fails to boot and if so where is it?

**Comment by AndreiLux** [comment]
Synapse disables itself if a reboot happens too fast after boot. If you don't have any issues manually applying the settings, then it's not a problem of the app.

Fix that hot boot and you fix the boot settings not applying.

**Comment by Anakha56** [comment]
Its strange because last night I did a complete reinstall of the by doing the required wipes and it still persists. Starting to think it is a hardware issue <_<. Thanks for the response will inestigate further on my end.

**Comment by faridahmalik** [comment]
Hi Andrei，I'm enjoying your amazing Perseus 15.2 and everything works perfect.Only one thing，it's a little bit laggy compared to Adam kernel and I don't know why.Especially after I quited an app then swipe instantly it lags seriously.Is it becuz the Synapse settings？How can I change it to reduce lag.Thx ！XD

**Comment by AndreiLux** [comment]
I don't really have any reason to update it right now. 

Any improvements that could be done I don't want to invest large amount of time on.

**Comment by AndreiLux** [comment]
Depends on the launches that'll happen in the next months.

**Comment by archer999** [comment]
Hey andrei!, are this perseus kernel improve charging time? My phone now only need 1,5H charging time instead 2H, is this normal? 
Btw I use CM11

**Comment by AndreiLux** [comment]
The default charging settings are the same as stock.

**Comment by IgoA** [comment]
Good Day To You Andrei! Can You change a few lines in default.prop and rc files to make kernel insecure? I am making my own Samsung-Based very small rom and that will help much. Now i am changing things on /system from recovery and it takes too much time (((

**Comment by AndreiLux** [comment]
No.

**Comment by Anakha56** [comment]
Hey Andrei, did the kernel release for the Note 3 reveal any extra goodies for the S4? _fingers crossed_

/Although I suspect Samsung would have reused old sources and made it look new... _edit_ Or it is for the non Exynos devices...

**Comment by AndreiLux** [comment]
A new input booster mechanism and equalizer settings for video recording. But the 5420 platform is diverging too much so I don't know what of those will end up here.

**Comment by Anakha56** [comment]
Andrei is there a reason why this kernel takes longer to reboot/shutdown than others? I noticed whenever I request a reboot or shutdown the screen goes black but I still have the blue notification light and the backlight keys on and it takes quite awhile to reboot/shutdown. Also I noticed on the Samsung model screen it flickers twice before booting into boot screen, is that normal?

 /think I need to do a clean install of the ROM again...

**Comment by maxedrom** [comment]
Hello, the download links of the Perseus Kernel https://github.com/AndreiLux/Perseus-UNIVERSAL5410/wiki

doesn't work. Can you check?

Thanks

**Comment by Anakha56** [comment]
So nothing new for us Samsung ROM guys Andrei? Will we see any benefit to flashing 16? I am tempted to flash the latest CM since it has finally been accepted so this is cool to see.

Also I noticed if I use BusyBox Pro from the Play Store (old purchase for my HTC Desire) and update BusyBox it breaks Synapse with a Synapse error "No UCCI Device" I think it goes. Could the sound issues be a BusyBox issue? The only reason why I had thought this was because Chainfires newest app (Pry-Fi) killed Wifi on some devices and it was due to different implementations of BusyBox. Just a thought I had...

**Comment by Anakha56** [comment]
Andrei I have flashed the latest 16.1 on WanamLite and I have this interesting message when opening Synapse on the CPU tab: "SLiveLabel has failed: com.af.synapse,utils.RunCommandFailedException: Must use '-v',=,- or +". I have done a global reset and then rebooted the phone but the message persists. No idea what it means or how it affects things but just letting you know :).

**Comment by ghost** [comment]
Hi Andrei is this for i9500 4.3?. As when flashed zip file and tar file Synapse wold not open?. Either im nuts or completely missing something. Cheers for your time,

**Comment by Anakha56** [comment]
Synapse is working fine on my end and I am on a Samsung ROM, i9500.

**Comment by ghost** [comment]
Dam... Ok... Thanks for the reply. 

Ill try again! :)

**Comment by Anakha56** [comment]
Have your tried clearing the cache or clearing the data of the app and seeing if it opens then?

**Comment by ghost** [comment]
Yeah tried all the normal stuff.. Cache, clearing app data and reinstalling the apk and trying the playstore download. After tapping the Synapse app the app open but wont load the data. ill try a fresh download for 16.1 and install again. Cheers

**Comment by ghost** [comment]
Ok, Tried a fresh 16.1 download, wiped cache again, dalvik, and app data. Now it crashes on start up. Back to 15.2.

**Comment by ghost** [comment]
Got it working, kinda. I have installed it from root explorer. It now opens. Think i have had two issues. One with Getting root and app.

**Comment by AndreiLux** [comment]
Do I look like a fortune teller? Try it yourself.

**Comment by Anakha56** [comment]
Xphoid calm the heck down. The ROM was only released yesterday and not everyone has a super fast Internet connection to download, flash and test. Heck Andrei is 99.999999% recurring busy with real life. Be respectful and exercise some patience...

**Comment by ednan23** [comment]
hey AndreiLux..

I've been enjoying your kernel since 4.2.2.. just wanna ask, does this work on stock 4.4.2? thanks a lot. :)

**Comment by AndreiLux** [comment]
No

**Comment by Dnssuffix** [comment]
Again Thanks a Lot for the release that support Kitkat users. A masterpiece from a MasterClass Dev. Thanks Andrei :)

**Comment by Anakha56** [comment]
Thanks for the new kernel. Flash went off without a hitch, now to see the stability side of it :). I can't believe the A15 cores can get as high (and probably higher than) 60'C! _shock_

Andrei off topic question, but after seeing the S5 are you going to stay with Samsung and the Exynos side of life or are you planning to jump to another device?

**Comment by advatprashr** [comment]
Hey andreilux a15 cores are not working anymore on apha18

**Comment by educanst** [comment]
Hi. A15 cores are not activating after alpha18 update on 4.4.2

**Comment by AndreiLux** [comment]
A15 are working perfectly.

**Comment by educanst** [comment]
I set governor to performance and set max at 1800, min 200, but cpu stays at 1300(A7).

**Comment by Dnssuffix** [comment]
Im using 4.4.2 TW and Perseus 18. A15 is working perfectly, and remember A15 doesn't work all the time, it depends on the system load by Default.

**Comment by educanst** [comment]
Problem was power saving mode. It was blocking A15 cores. Wasn't that much agressive at 4.3

**Comment by Dnssuffix** [comment]
WiFi tethering is not working :( KK 4.4.2 sam , Perseus 18 . 
Please fix this issue :(

**Comment by mamilux** [comment]
Andrei Please Look One Time Benchmark Scores On Your Device, because very Low Scores And Synapse When Boot Phone Very Slow And restarting Phone one time!Stock Rom  I9500 4.4.2. I want on my device Sound up with synapse :(

**Comment by AndreiLux** [comment]
This issue was a bad idea. I don't want spam on my Github. Closed.

**Comment by mamilux** [comment]
Andrei  Look at me 5 minutes ago i make flash kernel again but it was same results please belive me.I allways offer to your kernel all my friends
