### ISSUE TITLE
Battery Drain!!

### ISSUE THREAD

**Issue by Princeteam** [AndreiLux/Perseus-UNIVERSAL5410#35]
Hi. this kernel is drinking battery. and i cant back to stock kernel.
This morning i have 100% battery 40 min later its 90, 1hour later its 75 and at 2.45 its finished with no use.
i try to turn back stock kk kernel (i have backup) its get bugged.its showing %0 battery and no apps no signal ...etc

**Comment by AndreiLux** [comment]
Can't help you. It's running fine for everybody else including me.

**Comment by icemodding** [comment]
I have the same problem with the battery, but there is an important UNDERVOLT perform battery drain.
