### ISSUE TITLE
Charge Issue and A15 cores

### ISSUE THREAD

**Issue by emreyalcin2000** [AndreiLux/Perseus-UNIVERSAL5410#37]
Rom:Samsung stock I9500UBUFNB4

Hi Andrei, after upgrading 4.4.2 and perseus a18, phone crashes when I try to charge when the device off, or during charging when I shut down the phone. Battery image displays on the screen for about 2-3 seconds then device turns off and only can be opened by removing the battery.

Also A15 cores do not kick in, sometimes 3-4 sec during the boot up but later stuck on max 1200mhz mostly on 600mhz even in hard usage and no deep sleep mode. Battery empties in 6 hours.

**Comment by advatprashr** [comment]
I am suffering from all those problems too! A15 never works and battery drain is pretty huge . Alarm never goes becuase every night phone shuts down by zero battery , this never happens on stock kernel

**Comment by AndreiLux** [comment]
Please stop reporting this nonsense on A15 and frequency issue - it has nothing to do with the kernel itself. If you're not capable of giving me technical information on it I could care less because it's absolutely unreproducible to me any many others. 

Turn off your savings modes, update your modems and do a complete shutdown such as everybody else. Otherwise I'm not interested in these complaints.

I'm just going to keep this open because the LPM charging issue is actually valid.

**Comment by emreyalcin2000** [comment]
About technical details I can say what I did in order to test it. 

My rom is samsung stock KOT49H.I9500UBUFNB4 and my baseband version is I9500XXUFNC1 and as far as I know they are the latest available version.

I completely wiped my phone, remove sdcard, and flash latest firmware with odin 3.09 without problems. Then before flashing perseus kernel, I used my phone around 24hrs and with cpu spy I can confirm I had no problems with cores frequency and deep sleep. Also charging during the phone is off I did not have any problems.

Then I flashed perseus kernel, flashed cache then used my phone around 12hrs. On cpu spy, there is no deep sleep duration and highest frequency is 1200mhz, but most of the time 250 and 600 mhz were used. Also I used antutu stress test in order to achieve high cpu usage and frequency and I observed the cpu situation on synapse and it never used a15 cores so stuck on 1200 mhz. And after perseus charging issue appears. Hope these info will help.

**Comment by AndreiLux** [comment]
> Hope these info will help.

No they don't. You gave me nothing beyond "it doesn't work". I'm not going to continue to dwell on this without actual information in the form of checking CPUFreq policies and having actual logs to back it up.
