### ISSUE TITLE
Mami

### ISSUE THREAD

**Issue by mamilux** [AndreiLux/Perseus-UNIVERSAL5410#39]
What Ever happend  I wait from U Make correct this problem. I was Told u before ı want use the "Synapse" for best sound on my device. After flash V18 my all benchmark scores falls working only A7 But A15 :( 
Please Andrei I'm Flash 10 time tried all wipe same results.

**Comment by ghost** [comment]
Bro... this issue been covered briefly in one of the other logs. If its a huge drama for ya flash the stock kernel. Theres no point opening a log and complaining about benchmark scores when most know they are pointless.

**Comment by ghost** [comment]
https://github.com/AndreiLux/Perseus-UNIVERSAL5410/issues/37

**Comment by AndreiLux** [comment]
> [If you are not able to comprehensibly formulate your issue in a detailed way and with a minimum amount of effort and common sense, you are not welcome and you should avoid using the tracker.](https://github.com/AndreiLux/Perseus-UNIVERSAL5410/wiki)

Please keep the idiotic posts to XDA, you're no longer welcome here.

**Comment by zetlaw** [comment]
Andrei can you tell us please what rom are you using ? 
I created my own Recovery ZIP package which is Fully stock and attached your kernel.  
the Rom is ODEXED and i still have problems with A15 and L2_HSIC.   it seems those problems occurs on ODEXED roms, is that a possibility ?

**Comment by AndreiLux** [comment]
Running my own stock. Don't have issues with odexed system, and I doubt it would be possible.

**Comment by zetlaw** [comment]
O.k i think im making progress.
When disabling Synapse from Autorun on start the device has A15 cores.  but after few Seconds-Minutes is stuck and restart. im guessing because of non default Voltages values.

**Comment by zetlaw** [comment]
OK. i dont know what exactly I've done but the following operations fixed it.
Removed : Stweaks, Trickstermod, SetCPU or anyother cpu control program.
Downgrade SYnapse to 0.20 version ( the one that included in the kernel) 
Wipe synapse data and cache.   wipe system cache. reboot.  set synapse values to -0.12.5 to all Votages values.   now i have a working Perseus kernel.

**Comment by AndreiLux** [comment]
Wiping or using an earlier Synapse will have no effect at all on any of that.

**Comment by zetlaw** [comment]
in addition i also  disabled start-up programs using start-up manager
software update, klms agent, WIFI-direct, ANT HAL service, FWupgrade, gear manager, watchon, Samsung learning, traver wallpepr  google play movies, Backup, Samsung syncadapter
i don't know what  but something just fixed it.  i am enjoying the kernel almost 24 hours since i did those operations.

**Comment by zetlaw** [comment]
Again. i restarted my device to fix a file in system/lib and  i got Wakelock problem with A15 core not working.  i have a logcat  i hope you can figure this out.
you're our only hope with this device.
https://mega.co.nz/#!8xFziLxD!tdiuYZEe8da9XkUEcAzuPxrkiwM6Gmqf7Ib5nXx9Zn4
