### ISSUE TITLE
Wifi tethering won't work in 4.4.2

### ISSUE THREAD

**Issue by mizagyu** [AndreiLux/Perseus-UNIVERSAL5410#40]
GS4 I9500
Tested on multiple ROMs (omega, nameless, stock)

Issue:

Wifi tethering may be turned on via any app and/or built in function, will say tethering is active, but nothing is sent out signal wise.

usb and bluetooth tether work fine.

Only affected by 17 and newer versions. 

---

In 4.3 Roms and older versions of your kernel, tething works as supposed to.

**Comment by AndreiLux** [comment]
The stock sources have the same issue on a vanilla kernel, can't do anything about it.

**Comment by zetlaw** [comment]
i think maxfu made it work.  his  V11 has whole other problems like unable to control A7 Speeds (650 750) and few unexpected reboots.  
but WIFI tether works on Odexed Kitkat rom.
his using OSRC 4.4 sources.

**Comment by AndreiLux** [comment]
I'll check it on the weekend.

**Comment by zetlaw** [comment]
thanks man i am  really appreciate that. 
went back to 4.3 to use your amazing kernel :-).

**Comment by mizagyu** [comment]
Tested the maxfour kernel, wifi tether works, but the rest of the kernel is
too glitchy for me. Im a loyalist to the perseus "brand", even at its most
glitchy days it runs best for me.
