### ISSUE TITLE
losing modem

### ISSUE THREAD

**Issue by rahulraimarine** [AndreiLux/Perseus-UNIVERSAL5410#41]
Losing modem every time I flash the kernel on a number of ROM. Ramdisk needs to be updated.

**Comment by AndreiLux** [comment]
Good for you.

**Comment by icemodding** [comment]
:P

**Comment by rahulraimarine** [comment]
As you wish..... Sarcasm is not an answer to everything. Learn to respect. Thanks for your good work anyway.
