### ISSUE TITLE
(not major) Recommended modem?

### ISSUE THREAD

**Issue by Anakha56** [AndreiLux/Perseus-UNIVERSAL5410#43]
Morning Andrei,

Quick question, but what modem would you recommend for your kernel? The only reason why I ask is because I am using the Chinese modem due to the improvement it had for CM11 and I am seeing massive wakelocks on l2_hsic, currently it has kept my phone awake for 47 minutes and woken the phone up 4560 times. I will be going on a modem flashing spree today to find the right one but I am curious to know what you think would be a good modem?

BTW I don't see this issue with stock Omega kernel or maxfour kernel.

_edit_ I am now using a Samsung ROM and not CM11...

**Comment by Anakha56** [comment]
I have tried multiple modems but with this kernel my l2_hsic goes through the roof :(. I am now using the modem for my country and it still gets massive wakelocks in the 16 minutes my phone has been awake since reboot I have had 1088 wakelocks with l2_hsic keeping the phone awake for 10m 21s. Andrei if I can help in any way to diagnose this issue please let me know. For now I will be going back to Omega stock...

**Comment by AndreiLux** [comment]
Don't have any recommendation. Modem-space is totally closed off from the rest of the phone. There might as well be unicorns in there.

**Comment by ghost** [comment]
You could try the XXUFNC2/1119314 firmware.. Looks like the changelist is higher than XXUFNC1/923538. Maybe itll help with your issues.

**Comment by Anakha56** [comment]
Thanks for the suggestion. I am currently running a NC2 ROM with a NC1 modem, looking for a NC2 modem now.

lol I wish I had unicorns in my modem! :p I will probably see my battery % increase and never decrease :p.

@AndreiLux Google searching this error for the i9500 shows results that are mainly focused on this kernel. Like I said if you have any idea on how I can help just let me know. Also is it possible to see l2_hsic commands(?) in logcat? Or would it be under another log file?

_edit_ Ignore, idiot just found the XDA thread with a fix in the build.prop. Investigating now. My apologies for wasting your time. :)
