### ISSUE TITLE
Links dead...

### ISSUE THREAD

**Issue by Tromick** [AndreiLux/Perseus-UNIVERSAL5410#46]
Links dead can u upload again? I don't trust other links... Also i want to ask. Can i use it Omega v27 TW Kitkat ROM? I was tried another kernel but my phone bootloop...

**Comment by AndreiLux** [comment]
I had to make space on my Dropbox, re-uploaded them here: https://github.com/AndreiLux/Perseus-UNIVERSAL5410/releases

**Comment by Tromick** [comment]
Can i use it Omega v27 TW Kitkat ROM? I was tried another kernel but my phone bootloop...
