### ISSUE TITLE
Fading in / out LED

### ISSUE THREAD

**Issue by cmd512** [AndreiLux/Perseus-UNIVERSAL5410#9]
Had this on Perseus for S3, would be great to have on the S4!

**Comment by AndreiLux** [comment]
Will be worked on sometime down the road.

**Comment by cmd512** [comment]
No problem, definitely a feature instead of a necessity... thanks!

**Comment by AndreiLux** [comment]
You wouldn't believe the amount of shit I had to do to get this working... That'll be a commit message worth reading.

**Comment by cmd512** [comment]
Haha, looking forward to it!
